/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fairmoney;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserStats extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2229852454901600716L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserStats\",\"namespace\":\"com.fairmoney\",\"fields\":[{\"name\":\"user_id\",\"type\":\"int\"},{\"name\":\"total_transactions_count\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserStats> ENCODER =
      new BinaryMessageEncoder<UserStats>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserStats> DECODER =
      new BinaryMessageDecoder<UserStats>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserStats> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserStats> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserStats> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserStats>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserStats to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserStats from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserStats instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserStats fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int user_id;
   private long total_transactions_count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserStats() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param total_transactions_count The new value for total_transactions_count
   */
  public UserStats(java.lang.Integer user_id, java.lang.Long total_transactions_count) {
    this.user_id = user_id;
    this.total_transactions_count = total_transactions_count;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return total_transactions_count;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.Integer)value$; break;
    case 1: total_transactions_count = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public int getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(int value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'total_transactions_count' field.
   * @return The value of the 'total_transactions_count' field.
   */
  public long getTotalTransactionsCount() {
    return total_transactions_count;
  }


  /**
   * Sets the value of the 'total_transactions_count' field.
   * @param value the value to set.
   */
  public void setTotalTransactionsCount(long value) {
    this.total_transactions_count = value;
  }

  /**
   * Creates a new UserStats RecordBuilder.
   * @return A new UserStats RecordBuilder
   */
  public static com.fairmoney.UserStats.Builder newBuilder() {
    return new com.fairmoney.UserStats.Builder();
  }

  /**
   * Creates a new UserStats RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserStats RecordBuilder
   */
  public static com.fairmoney.UserStats.Builder newBuilder(com.fairmoney.UserStats.Builder other) {
    if (other == null) {
      return new com.fairmoney.UserStats.Builder();
    } else {
      return new com.fairmoney.UserStats.Builder(other);
    }
  }

  /**
   * Creates a new UserStats RecordBuilder by copying an existing UserStats instance.
   * @param other The existing instance to copy.
   * @return A new UserStats RecordBuilder
   */
  public static com.fairmoney.UserStats.Builder newBuilder(com.fairmoney.UserStats other) {
    if (other == null) {
      return new com.fairmoney.UserStats.Builder();
    } else {
      return new com.fairmoney.UserStats.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserStats instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserStats>
    implements org.apache.avro.data.RecordBuilder<UserStats> {

    private int user_id;
    private long total_transactions_count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fairmoney.UserStats.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.total_transactions_count)) {
        this.total_transactions_count = data().deepCopy(fields()[1].schema(), other.total_transactions_count);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UserStats instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fairmoney.UserStats other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total_transactions_count)) {
        this.total_transactions_count = data().deepCopy(fields()[1].schema(), other.total_transactions_count);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public int getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public com.fairmoney.UserStats.Builder setUserId(int value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public com.fairmoney.UserStats.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_transactions_count' field.
      * @return The value.
      */
    public long getTotalTransactionsCount() {
      return total_transactions_count;
    }


    /**
      * Sets the value of the 'total_transactions_count' field.
      * @param value The value of 'total_transactions_count'.
      * @return This builder.
      */
    public com.fairmoney.UserStats.Builder setTotalTransactionsCount(long value) {
      validate(fields()[1], value);
      this.total_transactions_count = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'total_transactions_count' field has been set.
      * @return True if the 'total_transactions_count' field has been set, false otherwise.
      */
    public boolean hasTotalTransactionsCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'total_transactions_count' field.
      * @return This builder.
      */
    public com.fairmoney.UserStats.Builder clearTotalTransactionsCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserStats build() {
      try {
        UserStats record = new UserStats();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.total_transactions_count = fieldSetFlags()[1] ? this.total_transactions_count : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserStats>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserStats>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserStats>
    READER$ = (org.apache.avro.io.DatumReader<UserStats>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.user_id);

    out.writeLong(this.total_transactions_count);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.user_id = in.readInt();

      this.total_transactions_count = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.user_id = in.readInt();
          break;

        case 1:
          this.total_transactions_count = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










